//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araba()
        {
            this.KiraKayit = new HashSet<KiraKayit>();
        }
    
        public string arabaId { get; set; }
        public string arabaadi { get; set; }
        public string arabakategori { get; set; }
        public Nullable<int> kiralikdurum { get; set; }
        public string vites { get; set; }
        public string imgUrl { get; set; }
        public int arabaModel { get; set; }
        public int kirUcret { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiraKayit> KiraKayit { get; set; }
    }
}
