//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiraKayit
    {
        public string kiraKayitId { get; set; }
        public string kimKiraladi { get; set; }
        public string kimeKiraladi { get; set; }
        public string kirTarih { get; set; }
        public string iadeTarih { get; set; }
        public string kirArabaId { get; set; }
    
        public virtual Araba Araba { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual Uye Uye1 { get; set; }
    }
}
